{% set name = "superqt" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a37df244a2d6e4387e865cdedabe925798b3352ab9cdc52f60701eb12d907960

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pep517
    - setuptools_scm
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - qtpy
    - typing-extensions >=3.10.0.0

test:
  imports:
    - superqt
  requires:
    - pip
    - pyqt
  commands:
    - pip check

about:
  home: https://github.com/napari/superqt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Missing widgets and components for PyQt/PySide
  description: |
    Superqt aims to provide high-quality community-contributed Qt widgets
    and components for PyQt & PySide that are not provided in the native
    QtWidgets module, such as range sliders, float sliders, and other 
    extended widgets.
  dev_url: https://github.com/napari/superqt

extra:
  recipe-maintainers:
    - tlambert03
    - sofroniewn
    - jni
    - goanpeca
