{% set name = "superqt" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1037a2cef11afb597c2f3c47b532b5e8c9143e8ebed5b1b8eba823524378118

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - hatch
    - hatch-vcs
    - python >=3.7
    - pip
  run:
    - packaging
    - pygments>=2.4.0
    - python >=3.7
    - qtpy>=1.1.0
    - typing-extensions

test:
  imports:
    - superqt
  requires:
    - pip
    - pyqt
  commands:
    - pip check

about:
  home: https://github.com/pyapp-kit/superqt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Missing widgets and components for PyQt/PySide
  description: |
    Superqt aims to provide high-quality community-contributed Qt widgets
    and components for PyQt & PySide that are not provided in the native
    QtWidgets module, such as range sliders, float sliders, and other 
    extended widgets.
  dev_url: https://github.com/pyapp-kit/superqt

extra:
  recipe-maintainers:
    - tlambert03
    - sofroniewn
    - jni
    - goanpeca
