{% set name = "superqt" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af80d5687ec75df6c3e54119ee895e42f79742ed326684c79425414b5c20f1e3

build:
  number: 0
  skip: True  # [py<38 or s390x]
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - pygments >=2.4.0
    - qtpy >=1.1.0
    - typing_extensions >=3.7.4.3,!=3.10.0.0

test:
  imports:
    - superqt
  requires:
    - pip
    - pytest
    - pytest-qt
    - pyqt
    - numpy
  source_files:
    - pyproject.toml
    - tests
  commands:
    - pip check
    # Skip tests that need pint.
    - pytest -v --ignore=tests/test_quantity.py tests -k "not test_multistate"  # [win]

about:
  home: https://github.com/pyapp-kit/superqt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Missing widgets and components for PyQt/PySide
  description: |
    Superqt aims to provide high-quality community-contributed Qt widgets
    and components for PyQt & PySide that are not provided in the native
    QtWidgets module, such as range sliders, float sliders, and other 
    extended widgets.
  dev_url: https://github.com/pyapp-kit/superqt
  doc_url: https://pyapp-kit.github.io/superqt

extra:
  recipe-maintainers:
    - goanpeca
    - jni
    - sofroniewn
    - tlambert03
