{% set name = "superqt" %}
{% set version = "0.8.1" %}

# Skip tests on linux as our builders do not have X11 / opengl available.
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9a567e621c2dea0ce4c6c2f7e2237c09c52255e9848ca1594c9a957e2ecb08a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - pygments >=2.4.0
    - qtpy >=2.4.0
    - typing_extensions >=4.5.0  # [py<313]
    - typing_extensions >=4.12.0  # [py>=313]
  run_constrained:
    # cmap
    - cmap >=0.2
    # pyqt6
    - pyqt6 >=6.4.0,!=6.6  # [py<312]
    - pyqt6 >=6.7.0,!=6.6  # [py>=312]
    # pyside6
    - pyside6 >=6.4.0,!=6.5.0,!=6.5.1,!=6.6.2  # [py<312]
    - pyside6 >=6.7.0  # [py>=312]
    # quantity
    - pint>=0.21

test:
  source_files:
    - pyproject.toml
    - tests
  imports:  # [not linux]
    - superqt  # [not linux]
  commands:
    - pip check
    # OSX CI is headless - use Qt built-in offscreen rendering capability
    - export QT_QPA_PLATFORM=offscreen  # [unix]
    # Skip tests that need pint or pyconify
    # test_multistate fails with timeout on windows
    # test_press_move_release fails with timeout on osx
    # test_wrap_text and test_wrapped_eliding_label mail fail test tolerance
    - pytest -v --ignore=tests/test_quantity.py --ignore=tests/test_iconify.py tests -k "not (test_multistate or test_wrapped_eliding_label or test_wrap_text or test_press_move_release)"  # [not linux]
  requires:
    - pip
    - pytest
    - pytest-qt
    - pyqt
    - numpy

about:
  home: https://github.com/pyapp-kit/superqt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Missing widgets and components for PyQt/PySide
  description: |
    Superqt aims to provide high-quality community-contributed Qt widgets
    and components for PyQt & PySide that are not provided in the native
    QtWidgets module, such as range sliders, float sliders, and other
    extended widgets.
  dev_url: https://github.com/pyapp-kit/superqt
  doc_url: https://pyapp-kit.github.io/superqt

extra:
  recipe-maintainers:
    - goanpeca
    - jni
    - sofroniewn
    - tlambert03
  skip-true:
    - missing_imports_or_run_test_py
